;; The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;; Let us list the factors of the first seven triangle numbers:
;;      1: 1
;;      3: 1,3
;;      6: 1,2,3,6
;;     10: 1,2,5,10
;;     15: 1,3,5,15
;;     21: 1,3,7,21
;;     28: 1,2,4,7,14,28
;; We can see that 28 is the first triangle number to have over five divisors.
;; What is the value of the first triangle number to have over five hundred divisors?


(defun get-n-div (n)
  (let ((j 1) (n-div 1))
    (while (<= j (/ n 2))
      (if (= (% n j) 0 ) (setq n-div (+ 1 n-div)))
      (setq j (+ 1 j))
      )
    n-div
    )
  )

;; (get-n-div 28)

(defun euler-12 (max)
  (let ((i 0) (N 0) (n-div 0) (step 100))
    (while (<= n-div max)
      (if (= (% i step) 0) (print (format "i:%d N:%d n-div:%d" i N n-div)))
      (setq N (+ i N))
      (setq i (+ 1 i))
      (setq n-div (get-n-div N))
      )
    (kill-new (format "%d" n))
    (write-region (format "%d\n" n) nil "ans" 'append)
  )
)

(euler-12 500)
