;; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


(defun sum-fibonaci(MAX)
  (let ((p1 1)(h 1)(p2 1)(SUM 0))
    (while (<= p2 MAX)
      ; Check if the number is even
      (if (= (% p2 2) 0)
          (setq SUM (+ SUM p2))
          )
      (setq h p2)
      (setq p2 (+ p1 p2))
      (setq p1 h)
      )
    (kill-new (format "%d" SUM))
    ;; (print (format "The sum is %d" SUM))
    )
  )

(sum-fibonaci 4000000)
